server:
  port: 8087
spring:
  application:
    name: auth-service
  redis:
    host: 192.168.122.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

#读取公钥和私钥,配置公钥，私钥的位置
ly:
  jwt:
    pubKeyPath: D:\workspace2\ssh\id_rsa.pub # 公钥地址
    priKeyPath: D:\workspace2\ssh\id_rsa # 私钥地址
    user: #特殊标记，这些虽然与JWT有关，但却是用户登录相关属性，因此这样来配置
      expire: 30 #token过期时间，单位分钟
      cookieName: LY_TOKEN  #cookie的名称
      cookieDomain: leyou.com  #cookie的域,可以让leyou.com下的所有二级域名共享cookie
      minRefreshInterval: 15 #最小刷新间隔，单位分钟
    app:
      expire: 90000  #微服务认证申请token的有效时间,秒
      id: 10  #自己的id
      secret: ${spring.application.name} #自己的服务密钥
