server:
  port: 8085
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.122.128
    username: leyou
    password: leyou
    virtual-host: /leyou

ly:
  sms:
    accessKeyID: LTAIWrYWwCFEgbbV # 你自己的accessKeyId
    accessKeySecret: YghpoqD8s4aIOw7iOdPg4td2Uh7Cpt # 你自己的AccessKeySecret
    signName: 惠民消息 # 签名名称
    verifyCodeTemplate: SMS_165380435 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id