server:
  port: 8088
spring:
  application:
    name: privilege-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou?allowMultiQueries=true
    username: root
    password: root

  #注册进注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

    #mybatis配置
mybatis:
  type-aliases-package: com.leyou.privilege.entity
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.leyou: trace

mapper:
  wrap-keyword: "`{0}`"

ly:
  encoder:
    crypt:
      secret: ${random.uuid}
      strength: 10
  jwt:
    pubKeyPath: D:\workspace2\ssh\id_rsa.pub # 公钥地址
    privilege:
      id: 9
      secret: ${spring.application.name}
      headerName: privilege_token