spring:
  thymeleaf:
    cache: false
  application:
    name: page-service
  rabbitmq:
    host: 192.168.122.128
    username: leyou
    password: leyou
    virtual-host: /leyou
server:
  port: 8084
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

ly:
  static:
    itemDir: D:\develop\nginx-1.14.0\html\item
    item: item