server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
  rabbitmq:
    host: 192.168.122.128
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true  #是否开启重试
        initial-interval: 10000ms  #第一次重试的间隔时长
        max-interval: 80000ms  #最长重试间隔，超过这个间隔将不再重试
        multiplier: 2   #下次重试间隔的倍数，此处是2即下次重试间隔是上次的2倍
      exchange: ly.item.exchange   #交换机名，缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
    publisher-confirms: true #是否开启生产者确认机制，生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

#配置mybatis
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.leyou.item.entity
  configuration:
    map-underscore-to-camel-case: true

#全局修改关键词冲突问题
mapper:
  wrap-keyword: "`{0}`"
